**Project temperature summary**


In [2]:
import numpy as np

In [3]:
a1=np.array([13,29,10,22,10,23,14,31,7,32,15,32,14,30,11,22,6,27,12,	27,	-13,26,	13,	32,	6,	26,	6,	26,	15,	21,	8,	28,	7,	26,	14,	22,	13,	27,	10,	21,	12,	31,	12,	32,	15,	27,	13,	29,	14,	24,	12,	27,	8,	29,	12,	30,	11,	25,	15,	30,	7,	26,	6,	29,	10,	20,	12,	30,	10,	26,	9,	22,	12,	21,	10,	30,	7,	21,	9,	27,	12,	25,	9,	22,	15,	31,	6,	27,	15,	20,	6,	32,	10,	21,	12,	25,	10,	25,	13,	22,	12,	21,	7,	24,	14,	25,	15,	30,	13,	23,	11,	26,7,	21,	5,	21,	8,	22,	6,	20,	7,	19,	8,	8,	22,	6,3,	20,	6,	21,	8,	18,	6,	19,	7,	19,	2,	8,	22,	5,8,	19,	3,	19,	2,	19,	8,	18,	7,	20,	3,	3,	18,	7,8,	20,	4,	18,	8,	20,	6,	19,	3,21,	8,	2,	20,	5,7,	20,	9,	22,	-10,21,	12,	19,	8,	18,	10,	71,	18,	7,	7,	20,	7,	22,	7,	20,	11,	21,	11,	18,	10,	9,	19,	12,	12,	22,	11,	21,	12,	20,	8,	18,	9,	22,	11,	11,	19,	8,9,18,	10,	19,	7,	21,	12,	21,	8,	19,	10,	8,	18,	12])

In [4]:
a1

array([ 13,  29,  10,  22,  10,  23,  14,  31,   7,  32,  15,  32,  14,
        30,  11,  22,   6,  27,  12,  27, -13,  26,  13,  32,   6,  26,
         6,  26,  15,  21,   8,  28,   7,  26,  14,  22,  13,  27,  10,
        21,  12,  31,  12,  32,  15,  27,  13,  29,  14,  24,  12,  27,
         8,  29,  12,  30,  11,  25,  15,  30,   7,  26,   6,  29,  10,
        20,  12,  30,  10,  26,   9,  22,  12,  21,  10,  30,   7,  21,
         9,  27,  12,  25,   9,  22,  15,  31,   6,  27,  15,  20,   6,
        32,  10,  21,  12,  25,  10,  25,  13,  22,  12,  21,   7,  24,
        14,  25,  15,  30,  13,  23,  11,  26,   7,  21,   5,  21,   8,
        22,   6,  20,   7,  19,   8,   8,  22,   6,   3,  20,   6,  21,
         8,  18,   6,  19,   7,  19,   2,   8,  22,   5,   8,  19,   3,
        19,   2,  19,   8,  18,   7,  20,   3,   3,  18,   7,   8,  20,
         4,  18,   8,  20,   6,  19,   3,  21,   8,   2,  20,   5,   7,
        20,   9,  22, -10,  21,  12,  19,   8,  18,  10,  71,  1

In [5]:
a2=a1.reshape(4,4,7,2)

In [6]:
a2

array([[[[ 13,  29],
         [ 10,  22],
         [ 10,  23],
         [ 14,  31],
         [  7,  32],
         [ 15,  32],
         [ 14,  30]],

        [[ 11,  22],
         [  6,  27],
         [ 12,  27],
         [-13,  26],
         [ 13,  32],
         [  6,  26],
         [  6,  26]],

        [[ 15,  21],
         [  8,  28],
         [  7,  26],
         [ 14,  22],
         [ 13,  27],
         [ 10,  21],
         [ 12,  31]],

        [[ 12,  32],
         [ 15,  27],
         [ 13,  29],
         [ 14,  24],
         [ 12,  27],
         [  8,  29],
         [ 12,  30]]],


       [[[ 11,  25],
         [ 15,  30],
         [  7,  26],
         [  6,  29],
         [ 10,  20],
         [ 12,  30],
         [ 10,  26]],

        [[  9,  22],
         [ 12,  21],
         [ 10,  30],
         [  7,  21],
         [  9,  27],
         [ 12,  25],
         [  9,  22]],

        [[ 15,  31],
         [  6,  27],
         [ 15,  20],
         [  6,  32],
         [ 10,  21],

In [7]:
#Ans1
print(a2.ndim)
print(a2.shape)

4
(4, 4, 7, 2)


In [8]:
#Ans2
print(a2[:,:,0,:])

[[[13 29]
  [11 22]
  [15 21]
  [12 32]]

 [[11 25]
  [ 9 22]
  [15 31]
  [13 22]]

 [[ 7 21]
  [ 3 20]
  [ 8 19]
  [ 8 20]]

 [[ 7 20]
  [ 7 20]
  [12 22]
  [ 9 18]]]


In [9]:
#Ans 3
print(a2[:,:,1,:])

[[[10 22]
  [ 6 27]
  [ 8 28]
  [15 27]]

 [[15 30]
  [12 21]
  [ 6 27]
  [12 21]]

 [[ 5 21]
  [ 6 21]
  [ 3 19]
  [ 4 18]]

 [[ 9 22]
  [ 7 22]
  [11 21]
  [10 19]]]


In [10]:
print(a2[:,:,0:5,1])

[[[29 22 23 31 32]
  [22 27 27 26 32]
  [21 28 26 22 27]
  [32 27 29 24 27]]

 [[25 30 26 29 20]
  [22 21 30 21 27]
  [31 27 20 32 21]
  [22 21 24 25 30]]

 [[21 21 22 20 19]
  [20 21 18 19 19]
  [19 19 19 18 20]
  [20 18 20 19 21]]

 [[20 22 21 19 18]
  [20 22 20 21 18]
  [22 21 20 18 22]
  [18 19 21 21 19]]]


In [11]:
#Ans 4

ni = np.where(a2[0, :, :, 0] < 8)
ni

(array([0, 1, 1, 1, 1, 2], dtype=int64),
 array([4, 1, 3, 5, 6, 2], dtype=int64))

Check Data: Verify accuracy by comparing with reliable sources.

Flag or Remove: Mark or remove questionable data if it's wrong or doesn't fit.

Use Averages: Replace extreme values with average or median nearby.

Domain Expertise: Consider if odd values make sense in certain situations.

Smoothing: Apply techniques to reduce the impact of outliers.

Segment Data: Analyze segments separately if data varies.

Consult: Seek advice from experts if unsure.

Improve Process: Address potential errors in data collection.

In [12]:
valid_temp_range = (np.nan, 50)  # Replace 50 with the upper limit of valid temperatures

# Find the indices of outlier values
outlier_indices = np.where(np.logical_or(a2 < valid_temp_range[0], a2 > valid_temp_range[1]))

# Print the indices of outlier values
if len(outlier_indices[0]) > 0:
    print("Indices of outlier values:")
    for idx in range(len(outlier_indices[0])):
        month, week, day, temp_type = outlier_indices[0][idx], outlier_indices[1][idx], outlier_indices[2][idx], outlier_indices[3][idx]
        print(f"Month {month + 1}, Week {week + 1}, Day {day + 1}, Temp Type {temp_type}: Value {a2[month, week, day, temp_type]}")
else:
    print("No outlier values found in the dataset.")

Indices of outlier values:
Month 4, Week 1, Day 6, Temp Type 1: Value 71


In [13]:
valid_temp_range = (np.nan, 50)  # Replace 50 with the upper limit of valid temperatures


outlier_indices = np.where(np.logical_or(a2 < valid_temp_range[0], a2 > valid_temp_range[1]))


for idx in range(len(outlier_indices[0])):
    month, week, day, temp_type = outlier_indices[0][idx], outlier_indices[1][idx], outlier_indices[2][idx], outlier_indices[3][idx]
    

    neighboring_values = a2[month, week, day]
    neighboring_values = np.delete(neighboring_values, temp_type)
    
   
    a2[month, week, day, temp_type] = np.median(neighboring_values)


print("Modified Temperature Data:")
print(a2)



Modified Temperature Data:
[[[[ 13  29]
   [ 10  22]
   [ 10  23]
   [ 14  31]
   [  7  32]
   [ 15  32]
   [ 14  30]]

  [[ 11  22]
   [  6  27]
   [ 12  27]
   [-13  26]
   [ 13  32]
   [  6  26]
   [  6  26]]

  [[ 15  21]
   [  8  28]
   [  7  26]
   [ 14  22]
   [ 13  27]
   [ 10  21]
   [ 12  31]]

  [[ 12  32]
   [ 15  27]
   [ 13  29]
   [ 14  24]
   [ 12  27]
   [  8  29]
   [ 12  30]]]


 [[[ 11  25]
   [ 15  30]
   [  7  26]
   [  6  29]
   [ 10  20]
   [ 12  30]
   [ 10  26]]

  [[  9  22]
   [ 12  21]
   [ 10  30]
   [  7  21]
   [  9  27]
   [ 12  25]
   [  9  22]]

  [[ 15  31]
   [  6  27]
   [ 15  20]
   [  6  32]
   [ 10  21]
   [ 12  25]
   [ 10  25]]

  [[ 13  22]
   [ 12  21]
   [  7  24]
   [ 14  25]
   [ 15  30]
   [ 13  23]
   [ 11  26]]]


 [[[  7  21]
   [  5  21]
   [  8  22]
   [  6  20]
   [  7  19]
   [  8   8]
   [ 22   6]]

  [[  3  20]
   [  6  21]
   [  8  18]
   [  6  19]
   [  7  19]
   [  2   8]
   [ 22   5]]

  [[  8  19]
   [  3  19]
   [  2  19]


In [14]:

winter_max_temps = a2[0:4, :, :, 1] 


aw = np.mean(winter_max_temps)
aw


21.258928571428573

In [15]:
#13
dec_min_temps = a2[1, :, :, 0] 


wd = np.mean(dec_min_temps, axis=1)
wd

array([10.14285714,  9.71428571, 10.57142857, 12.14285714])

In [16]:
#14
dec_jan_temps = np.concatenate((a2[1, :, :, :], a2[2, :, :, :]), axis=0)


overall_avg_temp_dec_jan = np.mean(dec_jan_temps)
overall_avg_temp_dec_jan

14.857142857142858

In [23]:
#15
dec_jan_min_temps = np.concatenate((a2[1, :, :, 0], a2[2, :, :, 0]), axis=0)
least_temp = np.min(dec_jan_min_temps)
least_temp_index = np.argmin(dec_jan_min_temps)

# Determine the month, week, and day for the least temperature
month, day_week_index, day = np.unravel_index(least_temp_index, (2, 4, 7))
if month == 0:
    month_name = "December"
else:
    month_name = "January"
week = day_week_index + 1

print(f"Least temperature: {least_temp:.2f}°C")
print(f"Date of occurrence: Month: {month_name}, Week: {week}, Day: {day + 1}")

Least temperature: 2.00°C
Date of occurrence: Month: January, Week: 2, Day: 6


In [24]:
#16
feb_max_temps = a2[3, :, :, 1] 


max_temp_feb = np.max(feb_max_temps)
max_temp_feb_index = np.unravel_index(np.argmax(feb_max_temps), feb_max_temps.shape)


month = 3
week, day = max_temp_feb_index

print(f"Max temperature in February: {max_temp_feb:.2f}°C")
print(f"Date of occurrence: Month: February, Week: {week + 1}, Day: {day + 1}")

Max temperature in February: 22.00°C
Date of occurrence: Month: February, Week: 1, Day: 2


In [25]:
#17

nov_max_temps = a2[0, :, :, 1]

avg_max_temp_nov = np.mean(nov_max_temps)

days_below_avg_temp = np.where(nov_max_temps < avg_max_temp_nov)


print("Days in November with max temp below average:")
for day in days_below_avg_temp[0]:
    print(f"Day {day + 1}")

Days in November with max temp below average:
Day 1
Day 1
Day 2
Day 2
Day 2
Day 2
Day 2
Day 2
Day 3
Day 3
Day 3
Day 3
Day 3
Day 4
Day 4
Day 4


In [26]:
#18
a2_f = (a2 * 9/5) + 32

print("Temperature Data in Fahrenheit:")
print(a2_f)

Temperature Data in Fahrenheit:
[[[[55.4 84.2]
   [50.  71.6]
   [50.  73.4]
   [57.2 87.8]
   [44.6 89.6]
   [59.  89.6]
   [57.2 86. ]]

  [[51.8 71.6]
   [42.8 80.6]
   [53.6 80.6]
   [ 8.6 78.8]
   [55.4 89.6]
   [42.8 78.8]
   [42.8 78.8]]

  [[59.  69.8]
   [46.4 82.4]
   [44.6 78.8]
   [57.2 71.6]
   [55.4 80.6]
   [50.  69.8]
   [53.6 87.8]]

  [[53.6 89.6]
   [59.  80.6]
   [55.4 84.2]
   [57.2 75.2]
   [53.6 80.6]
   [46.4 84.2]
   [53.6 86. ]]]


 [[[51.8 77. ]
   [59.  86. ]
   [44.6 78.8]
   [42.8 84.2]
   [50.  68. ]
   [53.6 86. ]
   [50.  78.8]]

  [[48.2 71.6]
   [53.6 69.8]
   [50.  86. ]
   [44.6 69.8]
   [48.2 80.6]
   [53.6 77. ]
   [48.2 71.6]]

  [[59.  87.8]
   [42.8 80.6]
   [59.  68. ]
   [42.8 89.6]
   [50.  69.8]
   [53.6 77. ]
   [50.  77. ]]

  [[55.4 71.6]
   [53.6 69.8]
   [44.6 75.2]
   [57.2 77. ]
   [59.  86. ]
   [55.4 73.4]
   [51.8 78.8]]]


 [[[44.6 69.8]
   [41.  69.8]
   [46.4 71.6]
   [42.8 68. ]
   [44.6 66.2]
   [46.4 46.4]
   [71.6 42.8]]

 

In [27]:
#19

dec_avg_temps = a2[1, :, :, :].mean(axis=(1, 2))


sorted_data_dec = a2[dec_avg_temps.argsort()[::-1]]

print("Sorted Data for December:")
print(sorted_data_dec)

Sorted Data for December:
[[[[ 13  29]
   [ 10  22]
   [ 10  23]
   [ 14  31]
   [  7  32]
   [ 15  32]
   [ 14  30]]

  [[ 11  22]
   [  6  27]
   [ 12  27]
   [-13  26]
   [ 13  32]
   [  6  26]
   [  6  26]]

  [[ 15  21]
   [  8  28]
   [  7  26]
   [ 14  22]
   [ 13  27]
   [ 10  21]
   [ 12  31]]

  [[ 12  32]
   [ 15  27]
   [ 13  29]
   [ 14  24]
   [ 12  27]
   [  8  29]
   [ 12  30]]]


 [[[  7  20]
   [  9  22]
   [-10  21]
   [ 12  19]
   [  8  18]
   [ 10  10]
   [ 18   7]]

  [[  7  20]
   [  7  22]
   [  7  20]
   [ 11  21]
   [ 11  18]
   [ 10   9]
   [ 19  12]]

  [[ 12  22]
   [ 11  21]
   [ 12  20]
   [  8  18]
   [  9  22]
   [ 11  11]
   [ 19   8]]

  [[  9  18]
   [ 10  19]
   [  7  21]
   [ 12  21]
   [  8  19]
   [ 10   8]
   [ 18  12]]]


 [[[  7  21]
   [  5  21]
   [  8  22]
   [  6  20]
   [  7  19]
   [  8   8]
   [ 22   6]]

  [[  3  20]
   [  6  21]
   [  8  18]
   [  6  19]
   [  7  19]
   [  2   8]
   [ 22   5]]

  [[  8  19]
   [  3  19]
   [  2  19]
 

In [29]:
#22
# Calculate the difference between min and max temp for each day
temp_diff_per_day = a2[:, :, :, 1] - a2[:, :, :, 0]

print("Temperature Difference Between Min and Max Temp for Each Day:")
print(temp_diff_per_day)

Temperature Difference Between Min and Max Temp for Each Day:
[[[ 16  12  13  17  25  17  16]
  [ 11  21  15  39  19  20  20]
  [  6  20  19   8  14  11  19]
  [ 20  12  16  10  15  21  18]]

 [[ 14  15  19  23  10  18  16]
  [ 13   9  20  14  18  13  13]
  [ 16  21   5  26  11  13  15]
  [  9   9  17  11  15  10  15]]

 [[ 14  16  14  14  12   0 -16]
  [ 17  15  10  13  12   6 -17]
  [ 11  16  17  10  13   0 -11]
  [ 12  14  12  13  18  -6 -15]]

 [[ 13  13  31   7  10   0 -11]
  [ 13  15  13  10   7  -1  -7]
  [ 10  10   8  10  13   0 -11]
  [  9   9  14   9  11  -2  -6]]]


In [30]:
#23
# Calculate the difference between max temp of two consecutive days for each month
max_temp_diff_per_month = a2[:, :, 1:, 1] - a2[:, :, :-1, 1]

print("Temperature Difference Between Max Temp of Consecutive Days for Each Month:")
print(max_temp_diff_per_month)

Temperature Difference Between Max Temp of Consecutive Days for Each Month:
[[[ -7   1   8   1   0  -2]
  [  5   0  -1   6  -6   0]
  [  7  -2  -4   5  -6  10]
  [ -5   2  -5   3   2   1]]

 [[  5  -4   3  -9  10  -4]
  [ -1   9  -9   6  -2  -3]
  [ -4  -7  12 -11   4   0]
  [ -1   3   1   5  -7   3]]

 [[  0   1  -2  -1 -11  -2]
  [  1  -3   1   0 -11  -3]
  [  0   0  -1   2 -17   4]
  [ -2   2  -1   2 -19   3]]

 [[  2  -1  -2  -1  -8  -3]
  [  2  -2   1  -3  -9   3]
  [ -1  -1  -2   4 -11  -3]
  [  1   2   0  -2 -11   4]]]


In [31]:
#24
# Calculate the difference between min temp of two consecutive days for each month
min_temp_diff_per_month = a2[:, :, 1:, 0] - a2[:, :, :-1, 0]

print("Temperature Difference Between Min Temp of Consecutive Days for Each Month:")
print(min_temp_diff_per_month)

Temperature Difference Between Min Temp of Consecutive Days for Each Month:
[[[ -3   0   4  -7   8  -1]
  [ -5   6 -25  26  -7   0]
  [ -7  -1   7  -1  -3   2]
  [  3  -2   1  -2  -4   4]]

 [[  4  -8  -1   4   2  -2]
  [  3  -2  -3   2   3  -3]
  [ -9   9  -9   4   2  -2]
  [ -1  -5   7   1  -2  -2]]

 [[ -2   3  -2   1   1  14]
  [  3   2  -2   1  -5  20]
  [ -5  -1   6  -1  -4  15]
  [ -4   4  -2  -3   5  12]]

 [[  2 -19  22  -4   2   8]
  [  0   0   4   0  -1   9]
  [ -1   1  -4   1   2   8]
  [  1  -3   5  -4   2   8]]]


In [32]:

#25
temp_diff_per_day_all_months = a2[:, :, :, 1] - a2[:, :, :, 0]

# Combine the arrays from q.23 and q.24
combined_temp_diff = np.stack((min_temp_diff_per_month, max_temp_diff_per_month), axis=3)

print("Combined Difference Between Min and Max Temp for Each Day of All Months:")
print(combined_temp_diff)

Combined Difference Between Min and Max Temp for Each Day of All Months:
[[[[ -3  -7]
   [  0   1]
   [  4   8]
   [ -7   1]
   [  8   0]
   [ -1  -2]]

  [[ -5   5]
   [  6   0]
   [-25  -1]
   [ 26   6]
   [ -7  -6]
   [  0   0]]

  [[ -7   7]
   [ -1  -2]
   [  7  -4]
   [ -1   5]
   [ -3  -6]
   [  2  10]]

  [[  3  -5]
   [ -2   2]
   [  1  -5]
   [ -2   3]
   [ -4   2]
   [  4   1]]]


 [[[  4   5]
   [ -8  -4]
   [ -1   3]
   [  4  -9]
   [  2  10]
   [ -2  -4]]

  [[  3  -1]
   [ -2   9]
   [ -3  -9]
   [  2   6]
   [  3  -2]
   [ -3  -3]]

  [[ -9  -4]
   [  9  -7]
   [ -9  12]
   [  4 -11]
   [  2   4]
   [ -2   0]]

  [[ -1  -1]
   [ -5   3]
   [  7   1]
   [  1   5]
   [ -2  -7]
   [ -2   3]]]


 [[[ -2   0]
   [  3   1]
   [ -2  -2]
   [  1  -1]
   [  1 -11]
   [ 14  -2]]

  [[  3   1]
   [  2  -3]
   [ -2   1]
   [  1   0]
   [ -5 -11]
   [ 20  -3]]

  [[ -5   0]
   [ -1   0]
   [  6  -1]
   [ -1   2]
   [ -4 -17]
   [ 15   4]]

  [[ -4  -2]
   [  4   2]
   [ -2  -1]
   [